doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid:  App\Infrastructure\Persistence\Doctrine\CustomTypes\UuidType
            datetime_microseconds: App\Infrastructure\Persistence\Doctrine\CustomTypes\DateTimeWithMicroseconds

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Domain'
                prefix: 'App\Domain'
                alias: App